 # This is the config file used for the docker images.
  # It allows all users to do anything, so don't use it on production systems.
  #
  # Do not configure host and port under `listen` in this file
  # as it will be ignored when using docker.
  # see https://github.com/verdaccio/verdaccio/blob/master/docs/docker.md#docker-and-custom-port-configuration
  #
  # Look here for more config file examples:
  # https://github.com/verdaccio/verdaccio/tree/master/conf
  #
  # path to a directory with all packages
  storage: /verdaccio/storage/data
  plugins: /verdaccio/plugins
  web:
    # WebUI is enabled as default, if you want disable it, just uncomment this line
    #enable: false
    title: Verdaccio
  auth:
    kuzzle:
      url: localhost:7512
  # a list of other known repositories we can talk to
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      agent_options:
        keepAlive: true
        maxSockets: 40
        maxFreeSockets: 10
    github:
      url: https://npm.pkg.github.com
      auth:
        type: bearer
        token: <token goes here>
  packages:
    '@org/*':
      # scoped packages
      access: $authenticated
      publish: $authenticated
      unpublish: $authenticated
      proxy: github
    '**':
      # allow all users (including non-authenticated users) to read and
      # publish all packages
      #
      # you can specify usernames/groupnames (depending on your auth plugin)
      # and three keywords: "$all", "$anonymous", "$authenticated"
      access: $all
      # allow all known users to publish packages
      # (anyone can register by default, remember?)
      publish: $authenticated
      # if package is not available locally, proxy requests to 'npmjs' registry
      proxy: npmjs
  # To use `npm audit` uncomment the following section
  middlewares:
    audit:
      enabled: true
  # log settings
  logs: {type: stdout, format: pretty, level: http}
  # logs: {type: file, path: verdaccio.log, level: info}