name: Release

on:
  workflow_call:

  workflow_dispatch:
    inputs:

      npm_deploy:
        description: "Deploy to NPM"
        required: true
        default: true
        type: boolean

jobs:
  npm-deploy:
    name: Build and deploy release on NPM.js
    if: ${{ (github.event_name != 'workflow_dispatch' || inputs.npm_deploy) && (github.ref_name == 'master') }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install additional libraries
        uses: ./.github/actions/install-packages

      - name: Node version 14
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          registry-url: "https://registry.npmjs.org"
          scope: "@kuzzleio"

      - name: Install depedencies
        run: npm ci

      - name: Build depedencies
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GHP }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_NPM_PUBLISH: "true"
          SEMANTIC_RELEASE_SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
        run: npx semantic-release